### PR TITLE
Pass the new &format= param to IGV

### LINKED ISSUE #574: IGV integration broken
BAM tracks wouldn't load during the demo w/ the plot.ly folks today. Some kind of regression?

### PR DESCRIPTION
**Pull request by danvk**
Fixes #574 

I verified that this results in a correctly displayed VCF track for run 270, which has a VCF file ending in `part-r-00000`, rather than `.vcf`.

cc @arahuja

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/702)

### CODE REVIEW

**Comment by danvk** [comment]
I dropped the `maxlen` setting from `.jshintrc`. It was previously set to 200. I'm not sure what the value of such a large setting is, and I'd prefer not to split expected URLs onto multiple lines to satisfy the linter.

File: cycledash/static/js/examine/utils.js [hunk 1]
```diff
@@ -36,16 +36,17 @@ function makeIGVLink(run, igvHttpfsUrl) {
   }
 
   var nameFilePairs = [
```
Comment (ihodes) [inline cycledash/static/js/examine/utils.js]: This name doesn't match the value anymore; it could be clearer to have an array called 'tracks' of objects with keys like `name`, `type`, and `uri`.

Comment (danvk) [inline cycledash/static/js/examine/utils.js]: Sure, done.
