### PR TITLE
show bam names on runs page labels

### LINKED ISSUE #584: Display BAMs on run page
Perhaps my understanding of `Project` is incorrect here, but I've assuming a project has many BAMs and each run is using some subset of them (usually 2).  It would nice to display the BAMs that a run uses directly.  Specifically displaying the entered `name` when a BAM entry is created (this can be linked from the path, correct?)

### PR DESCRIPTION
**Pull request by ihodes**
fixes #584

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/593)

### CODE REVIEW

File: cycledash/static/js/examine/utils.js [hunk 1]
```diff
@@ -15,6 +15,7 @@ var LOCAL_IGV_HOST = 'localhost:60151';
  */
 function getIn(obj, path) {
   for (var i = 0; i < path.length; i++) {
+    if (_.isNull(obj) || _.isUndefined(obj)) return null;
```
Comment (danvk) [inline cycledash/static/js/examine/utils.js]: Document this behavior in the docstring.

File: tests/pdifftests/test.py [hunk 2]
```diff
@@ -26,15 +27,18 @@ class Runs(Base):
     window_size = [1280, 800]
     base_url = BASE
 
+    @hide('span.time')
```
Comment (danvk) [inline tests/pdifftests/test.py]: Did this not work? Most of the screenshot changes are from "10 days ago"→"1 month ago"

Comment (danvk) [inline tests/pdifftests/test.py]: err, scratch that. I was misinterpreting the diffs :/

Comment (danvk) [inline tests/pdifftests/test.py]: Ah, you also want to hide the time for `examine_comments-{edit,view}`, that's what I was seeing.

File: cycledash/static/js/runs/components/RunsPage.js [hunk 3]
```diff
@@ -308,13 +308,14 @@ var RunLabels = React.createClass({
                       .object()
                       .value();
     var labelTypes = [
-      ['tumor_bam_id', 'tumor', 'Has an associated tumor BAM'],
-      ['normal_bam_id', 'normal', 'Has an associated normal BAM'],
-      ['run', '', 'Has a running worker task'],
-      ['fail', '', 'Has a failed worker task']
+      [['tumor_bam' , 'name'], null, 'Tumor BAM'],
```
Comment (danvk) [inline cycledash/static/js/runs/components/RunsPage.js]: The `null` vs `''` distinction is a little cryptic here. How about inlining the calls to be more direct? Something like

```javascript
var get = k => utils.getIn(run, k) || utils.getIn(taskStates, k),
    tumorName = get(['tumor_bam', 'name']),
    labelTypes = [
      [tumorName, tumorName, 'Tumor BAM'],
      [get(['run']), '', 'Has a running worker task'],
      ...
    ];
```

**Comment by danvk** [comment]
Looks good, just a few comments.

File: tests/pdifftests/test.py (hunk 2 above)
Comment (ihodes) [inline tests/pdifftests/test.py]: Yeah, hiding those would be good; I noted in the commit msg that I hide those which were easily selectable. Didn't want to do nth-child selections to hide content; too brittle. Need to add a css class to the span containing the time in examine_comments-XX; I was thinking it could be done in another PR.

File: cycledash/static/js/examine/utils.js (hunk 1 above)
Comment (ihodes) [inline cycledash/static/js/examine/utils.js]: :+1:

File: cycledash/static/js/runs/components/RunsPage.js [hunk 4]
```diff
@@ -307,21 +307,23 @@ var RunLabels = React.createClass({
...
                       .value();
-    var labelTypes = [
-      ['tumor_bam_id', 'tumor', 'Has an associated tumor BAM'],
-      ['normal_bam_id', 'normal', 'Has an associated normal BAM'],
-      ['run', '', 'Has a running worker task'],
-      ['fail', '', 'Has a failed worker task']
+    var labelSpecs = [
+      {path: ['tumor_bam' , 'name'], usePathValue: true, title: 'Tumor BAM'},
+      {path: ['normal_bam', 'name'], usePathValue: true, title: 'Normal BAM'},
+      {path: ['run'], title: 'Has atitle: running worker task', cssClass: 'run'},
```
Comment (danvk) [inline cycledash/static/js/runs/components/RunsPage.js]: `Has atitle`

**Comment by danvk** [comment]
One typo, otherwise LG. Hiding the times on comments should just be a matter of adding the `time` CSS class to that element, yeah?

**Comment by ihodes** [comment]
Super, back to you.
